---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
  - ./minio-bearer.secret.sops.yaml
  - ./minio-bucket-bearer.secret.sops.yaml
