apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-servicemonitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  namespaceSelector:
    matchNames:
      - storage
  endpoints:
  - port: http
    path: /minio/v2/metrics/cluster
    interval: 30s
    bearerTokenSecret:
      name: minio-bearer
      key: token
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-bucket-servicemonitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  namespaceSelector:
    matchNames:
      - storage
  endpoints:
  - port: http
    path: /minio/v2/metrics/bucket
    interval: 30s
    bearerTokenSecret:
      name: minio-bucket-bearer
      key: token
