apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: minio-scrape
spec:
  scheme: HTTP
  authorization:
    type: Bearer
    credentials:
      name: minio-bearer
      key: token
  metricsPath: /minio/v2/metrics/cluster
  staticConfigs:
    - targets:
        - minio.storage.svc.cluster.local:9000
  relabelings:
    - action: replace
      targetLabel: job
      replacement: minio-scrape
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: minio-bucket-scrape
spec:
  scheme: HTTP
  authorization:
    type: Bearer
    credentials:
      name: minio-bucket-bearer
      key: token
  metricsPath: /minio/v2/metrics/bucket
  staticConfigs:
    - targets:
        - minio.storage.svc.cluster.local:9000
  relabelings:
    - action: replace
      targetLabel: job
      replacement: minio-scrape
