---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: minio-scrape
spec:
  scheme: HTTP
  bearerToken: "{{MINIO_BEARER_TOKEN}}"
  metricsPath: /minio/v2/metrics/cluster
  staticConfigs:
    - targets:
        - minio.storage.svc.cluster.local:9000
  relabelings:
    - action: replace
      targetLabel: job
      replacement: minio-scrape
