apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: observability
type: Opaque
stringData:
    values.yaml: ""
    alertmanager:
        config:
            receivers:
                - name: ENC[AES256_GCM,data:7cs1/vndxg==,iv:6Ji512/sdfSxZK78I99mjQSP4DHSiuEywA/SEb6FfHU=,tag:qbaXWcMehFJtnAYqiFUWRw==,type:str]
                  discord_configs:
                    - webhook_url: ENC[AES256_GCM,data:zyisKAls7msz4utEgK897aDTcORQcSEMjBXSTfQfROB91KvvigI5QOMKxv2tRVFyB4PzLgvFPIaWAIka2Hmfguowa5AcrKkZ1BeU24clxwAg/AB4sdN9w1Q95cqMrNOtZ0pLsAtXytyUIbJOMDZ/ueDZOwh+Z2vfcA==,iv:tWOmYXBSHrI46pkiwG4By9oRqkWX4BgaaoyX4p/jwG4=,tag:0c+m149w59VUn5zDZHKBQQ==,type:str]
                - name: ENC[AES256_GCM,data:s2TaTA==,iv:86RAGtVpRn4BaDYwBb8VmGQfJAhrjRcUA8WRe25FENk=,tag:OLQb5bWASoiC70KYvQtg6w==,type:str]
            route:
                receiver: ENC[AES256_GCM,data:qIQCOk++yg==,iv:aRet81ssjuO3HQRr/StlukZQ6H7I8c7eMQaP1QrhMTA=,tag:bzg+8Z7jjLUgahYrKa+/hA==,type:str]
                routes:
                    - matchers:
                        - ENC[AES256_GCM,data:ddDjtn+2dZbsmkC8XxF8V3Sy609Tfw==,iv:t2wdU+iCr6YCThhhSHJS9S/TBMLCkY9Poccm8c7EBBs=,tag:QVPMu0B+UYahxM1qtNb7GQ==,type:str]
                      receiver: ENC[AES256_GCM,data:k6yi2w==,iv:H5dU3pyaHu28N4jQKPFXbiT2erFQ340VL1OQk6iPAtY=,tag:x2gQId46yck5oZqbs0WE4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUGhaMFIyMUExNFhWNE02
            aXVSQnVnN2ZydEJJeElwSUIyNkNmMzROa1FJCit3YjJyTUdwQnJ4akJ4ci85SzBV
            ZXo3ak5mdnF3N0ljdjBYTGtzUUlkZnMKLS0tIEdJUE13NFo3akoyL3J0eDc2Z2FO
            QWlVOTQydFJmeFdSS0o0U1pnVXdnMzgKAZ1blxeTELpEo7VR/t/pVczktPNPlP7K
            0gPwvJe88vYv8qWj9HYCWhYNkAO8dCwf43VgDBMMOcI35raaBlKrWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T01:59:05Z"
    mac: ENC[AES256_GCM,data:Nx1b4gPNPu0QDHtDT4iKraL282di4BKdeJQMqEwz8Oq/VRcD2eOSfzXMUYBIAMZxFZY3YeIbtK3DJWmw8j+D2/RIa2xTGCaSojad966PKX0EmhS9rMzAQX1gNJYDx0ZhPamr8BbMV0Dhozq7UiA1q4xcyQo5qbRF82Wmb9dHEro=,iv:+AaGLOjeu0/b6QNhWq6wRLxA82+RufpF57CkFuU5Q3c=,tag:91Wr6X0mXMfVdSpZMRNmIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
