apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: observability
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:CKnA9jxWUIXOeyoLsO9ykGcZFJP5yATWfRz97Wv3wSzgU9+nK5t4LqSeeRtYolazU5BgaAPmt3wYX/zI/ZVpxjf5v8LWbK7nOfNckjm+5bNOGQ2+xjh2CDpgSixX18rwnMfQtxI4f8abVPnEv8PGHO7sArRMb/p/YfuTIq34J6Pa2Zy4hgNcRc9ZSW/1N+MBPzgGcPoTL/xvaRN+KnDVJwrGdkO1SoxMqxLw2ih2rOgcy1j5GVhB3TcTrGwu0p/NxXBxbHt/HWcJ/w4rYsTHYczbLsDPHGAPXLcnKB9nrkSyXz6mvdI=,iv:uTkrT4g/vGnKE/hWf5jPbEiml9M5qo7mYHJnx291eWc=,tag:FcGIp01zjm5Nwy98hSbP0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR05QZGk1R09Gcy82cjU1
            VGNSbnhIeUVkdmM4ZStUZ3dOWlRZdnZlOGtFCkdXbnZBMHltbDRielF0RGM5Tit6
            ekdCcjhVNSszbGV1TjF3ODhPRGxZVEkKLS0tIHpEWU05OVh2Nm5iZ3U2K3pITFdX
            dWZPTUZqcEpWSlZ6eUVtRlJiSG5OOGsKv4ZO4Mm5bJdoisgPvtOFpXRnJJglT2I0
            twaBznR0NhEvXz8D/kquZtiPugx4c96Z+gHBAEKFutRbAb8vBpeTfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T23:44:59Z"
    mac: ENC[AES256_GCM,data:gsiAHlI9FXIcV2ubHFhaiv6CdZ43Npn8/qWsXYPvW7bI0Xgaa2D/w0e4PVDna6MtxiYdQxBlvtTk+UXpAyPPiP7pFHvqwrC5LweXi663xKsVdLUtVmWez4jiuNUQdIRmKZmDK4WCw1xtn+KISTU/JyUi4l3X93dz1jPEIaeFjHI=,iv:Qy7F3IHxgC5py5g7av0kU4h6pEYGj5Il21Ljq2yycjA=,tag:UmIeJD+QZcmSsvV4ZdVIwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
