---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app discord-template-notifier
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      discord-template-notifier:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/morphy2k/rss-forwarder
              tag: 0.7.1
            env:
              TZ: "${TIMEZONE}"
            probes:
              liveness: &disabled
                enabled: false
              readiness: *disabled
              startup: *disabled
            resources:
              requests:
                cpu: 5m
                memory: 10M
              limits:
                memory: 64M
    persistence:
      config:
        type: secret
        name: discord-template-notifier-secret
        globalMounts:
          - path: /data/config.toml
            subPath: config.toml
            readOnly: true
