---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        image:
          repository: quay.io/minio/minio
          tag: RELEASE.2023-05-04T21-44-30Z
        env:
          TZ: America/Denver
          MINIO_UPDATE: "off"
          MINIO_BROWSER_REDIRECT_URL: https://minio.${SECRET_DOMAIN}
          MINIO_SERVER_URL: https://s3.${SECRET_DOMAIN}
        envFrom:
          - secretRef:
              name: minio-secret
        args: ["server", "/data", "--console-address", ":9001"]
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 750Mi
          # probes:
          #   liveness: &probes
          #     enabled: true
          #     custom: true
          #     spec:
          #       httpGet:
          #         path: /minio/health/live
          #         port: 9000
          #       initialDelaySeconds: 0
          #       periodSeconds: 10
          #       timeoutSeconds: 1
          #       failureThreshold: 3
          #   readiness: *probes
          startup:
            enabled: false
    service:
      main:
        enabled: true
        ports:
          http:
            port: 9001
          api:
            enabled: true
            port: 9000
    ingress:
      main:
        enabled: true
        ClassName: internal
        hosts:
          - host: &host minio.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9001
        tls:
          - hosts:
              - *host
      s3:
        enabled: true
        className: internal
        hosts:
          - host: &s3host s3.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9000
        tls:
          - hosts:
              - *s3host
    pod:
      securityContext:
        runAsUser: 1024
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 100
    persistence:
      config:
        enabled: true
        existingClaim: minio-nfs
        mountPath: /data
