# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-dst"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "${APP}-restic-secret"
    copyMethod: Snapshot
    volumeSnapshotClassName: "csi-ceph-blockpool"
    cacheCapacity: "${VOLSYNC_CACHE_CAPCITY}"
    storageClassName: "ceph-block"
    accessModes: 
      - ReadWriteOnce
    capacity: "${VOLSYNC_CAPACITY}"
