---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
  namespace: media
spec:
  sourcePVC: "${APP}"
  trigger:
    schedule: "00 11 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: "${APP}-restic-secret"
    cacheCapacity: "${VOLSYNC_CACHE_CAPCITY}"
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      hourly: 24
      daily: 10
      within: 3d
