---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-routed
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-routed
  template:
    metadata:
      labels:
        app: vpn-routed
      annotations:
        setGateway: "true"
    spec:
      containers:
      - name: dnsutils
        image: nicolaka/netshoot
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
