
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  # labels:
    # Avoid variable substitution of shell variables bellow
    # kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  #See https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gateway/values.yaml
  values:

    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.10.0
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: v3.37.0

        env:
        # - name:  VPN_SERVICE_PROVIDER
        #   value: set in secret
        - name:  VPN_TYPE
          value: wireguard
        - name:  VPN_INTERFACE
          value: wg0
        - name:  FIREWALL
          value: "off"
        - name:  DOT
          value: "off"
        # - name:  WIREGUARD_PRIVATE_KEY
        #   value: set in secret
        # - name:  WIREGUARD_PRESHARED_KEY
        #   value: set in secret
        # - name:  WIREGUARD_ADDRESSES
        #   value: set in secret
        # - name:  SERVER_COUNTRIES
        #   value: set in secret
        
        envFrom:
          - secretRef:
              name: vpn-gateway-config


        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - if [ $(wget -q -O- https://ipinfo.io/country) == 'NO' ]; then exit 0; else exit $?; fi
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3

        networkPolicy:
          enabled: true

          egress:
            - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
              ports:
              # VPN traffic
              - port: ${SECRET_VPN_GATEWAY_PORT}
                protocol: UDP
            - to:
              - ipBlock:
                  cidr: 10.0.0.0/8
    settings:
      # -- If using a VPN, interface name created by it
      VPN_INTERFACE: wg0
      # -- Prevent non VPN traffic to leave the gateway
      VPN_BLOCK_OTHER_TRAFFIC: true
      # -- If VPN_BLOCK_OTHER_TRAFFIC is true, allow VPN traffic over this port
      VPN_TRAFFIC_PORT: ${SECRET_VPN_GATEWAY_PORT}
      # -- Traffic to these IPs will be sent through the K8S gateway
      VPN_LOCAL_CIDRS: "10.69.0.0/16 10.96.0.0/16 192.168.1.0/24"
    
    # -- settings to expose ports, usually through a VPN provider.
    # NOTE: if you change it you will need to manually restart the gateway POD
    publicPorts:
    - hostname: transmission
      IP: 10 # must be an integer between 2 and VXLAN_GATEWAY_FIRST_DYNAMIC_IP (20 by default)
      ports:
      - type: udp
        port: 27071
      - type: tcp
        port: 27071

    routed_namespaces:
    - media
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        pullPolicy: Always
        tag: v3.9.0
      gatewayDefault: false
      gatewayLabel: routeToVPN
      gatewayAnnotation: routeToVPN
      namespaceSelector:
        label: "vpn-routed-gateway"