
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vpn-gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  #See https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gateway/values.yaml
  values:
    image:
      # repository: ghcr.io/angelnu/pod-gateway
      repository: jgilfoil/pod-gateway
      tag: v1.8.2@sha256:77e0810c4f609b3462ca208f3e7ce26f7259aefdadbbf3ca85ed07884a99fafa

    podAnnotations:
      reloader.stakater.com/auto: "true"

    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: v3.38.0@sha256:5522794f5cce6d84bc7f06b1e3a3b836ede9100c64aec94543cb503bb2ecb72f

        env:
        # - name:  VPN_SERVICE_PROVIDER
        #   value: set in secret
        - name:  VPN_TYPE
          value: wireguard
        - name:  VPN_INTERFACE
          value: wg0
        - name:  FIREWALL
          value: "off"
        - name:  DOT
          value: "off"
        - name: LOG_LEVEL
          value: "debug"
        - name: HEALTH_VPN_DURATION_INITIAL
          value: 30s
        # - name:  WIREGUARD_PRIVATE_KEY
        #   value: set in secret
        # - name:  WIREGUARD_PRESHARED_KEY
        #   value: set in secret
        # - name:  WIREGUARD_ADDRESSES
        #   value: set in secret
        # - name:  SERVER_COUNTRIES
        #   value: set in secret
        
        envFrom:
          - secretRef:
              name: vpn-gateway-config

        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "if [ '$(wget -q -O- https://ipinfo.io/country)' == 'NO' ]; then echo 'NO'; else echo 'not NO'; fi"
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3

        resources:
          requests:
            cpu: 5m
            memory: 64M
          limits:
            memory: 128M
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

      netshoot:
        enabled: true
        resources:
          requests:
            cpu: 5m
            memory: 10M
          limits:
            memory: 10M

        networkPolicy:
          enabled: true
          egress:
            - to:
              - ipBlock:
                  cidr: 10.0.0.0/8
            - to:
              - ipBlock:
                  cidr: 192.168.1.0/24

    settings:
      # -- If using a VPN, interface name created by it
      VPN_INTERFACE: wg0
      # -- Prevent non VPN traffic to leave the gateway
      VPN_BLOCK_OTHER_TRAFFIC: true
      # -- If VPN_BLOCK_OTHER_TRAFFIC is true, allow VPN traffic over this port
      VPN_TRAFFIC_PORT: ${SECRET_VPN_GATEWAY_PORT}
      # -- Traffic to these IPs will be sent through the K8S gateway
      VPN_LOCAL_CIDRS: "10.69.0.0/16 10.96.0.0/16 192.168.1.0/24"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.69.0.0/16 10.96.0.0/16 192.168.0.0/24"
    
    # -- settings to expose ports, usually through a VPN provider.
    # NOTE: if you change it you will need to manually restart the gateway POD
    publicPorts:
    - hostname: transmission
      IP: 10 # must be an integer between 2 and VXLAN_GATEWAY_FIRST_DYNAMIC_IP (20 by default)
      ports:
      - type: udp
        port: 27071
      - type: tcp
        port: 27071

    routed_namespaces:
    - media
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.10.0@sha256:a8ed630613de277244dfe203cd11d05905d7eeba8d8c41e399b02ee9a847b2f5
      gatewayDefault: false
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "vpn-routed-gateway"
