# yamllint disable
# VPN_SERVICE_PROVIDER: 
# SERVER_COUNTRIES: 
# WIREGUARD_PRIVATE_KEY: 
# WIREGUARD_PRESHARED_KEY: 
# WIREGUARD_ADDRESSES: 
apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-config
    namespace: vpn-gateway
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:v7G9HmBS,iv:yyvvdKaef1QsVSf3v+L4xv2/JdNiU8LPnt0r+QSZGik=,tag:tvJ/oMinDTrSt5CRU7ttWA==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:YT8SAnno,iv:0T4gxsNZ0yBOAzGXvM4yx6RdtkP8KSoB7N9C97r3Vv8=,tag:mSFjZgs0QdYan1gzfS4Hcg==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:fgNYLk2OlbR0yv9J2XbtfI/uFOSMJHoj/DeuVtBPnofQSqTzOxMs0CjTzBQ=,iv:AihyyvDOaQb8c37eLM93UUEYKw8M3yB2Vban8L6q+kI=,tag:1ZAwyiRduzAV2PI60VtIeQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:GQ71ZZx+NMxhSq5/lb3NTAhhYyzGDZE+bZcI6dDgq0/Bt27Q3Mty+P6nG08=,iv:gf5qnd67hbgDFeFq4Qm+ZsruYMSBn2EnxicsJ9QLk64=,tag:yH8GmuqNe6h0MTPavwWR3w==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:IA0wuMlCEiazvEte91mJo8rInydKcXnFsSiehPqh+Xub9C/DSJ90ac14S9Uid6TlDxd37EYRxUNZVhH6,iv:aoG7GIIDX3VfJM0e5+OxwT2v5U2QQIWeEh+MuTqwfhs=,tag:FOpMvH5XVWbFYsYOXlClLQ==,type:str]
    vpnConfigfile: ENC[AES256_GCM,data:B1/3xnR+9X/jxjyEVS+G3sqvmh84WgZqeCLjILwOCs39OHLFcRx1HiQcJKP022VEfHx5xcJdy94CJYoLHKW9Uvrp00VbGv9AQDVdCRfc72Z1vYXTQ6NJ8qi6RffY5mQOPqR4KFqJ3zkLuWdoUxPQUjxtuyAGCkXtZAh4ewvjZE9xo4wUQS5qo2US785g0u5o3+do0YaoWl5rx2/GzkIoKOeJp3w0gx3T8FuoJ2zjoVQjkvOm9WJ3QPwFZ+6YGeqzArg0K1TfI+JXsjkq6iiybERbJK2BFu+PvvNM8RLcVblg79mxFal2o28JfiFpt2mRfOPpNsYCQI1Kbf6GlSe8zyYfK3rrd+5zNTSlrWEQ0uLBQYKE9wdMe1obzClIM/RMwYBncCZt3Un5DjffaTn5XbjZNWdSFT5lY/4a4C77V4+UDITZn4HBuSeSkyD6Ha0wti6uQFb8TgQysdA8onlgRvREzXw3JYXAKf+0iQH9wmZpQ6Sq1dbK2sI4R6vKY4wjQdt+SzuerNeJEihUxbAl9cxfOoGFK1GtNeMXLy8lp4r7Eg==,iv:AKtuzzs4WWJL7bTxj5SZPOQE/RYZ4Te4XLdy/FSIpvM=,tag:PKByBN0PVVmgUn0LgSQtuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTndYZjNHam02a2w1S3k3
            dGMxbDA4c3E3VzZLdE43UWtjSko2NlpGamhzCkwydjljMXY3S2habWY5MUhOcGhu
            ZWxwQ2xhYTkyU0ZacnZFVWUwTTlSb1UKLS0tIDRMVkFYYzNKbFJHd253cmdaa3Qr
            U3dTaHYzL1JXVm8yc2swZ09uUEpVaHMKVImXOj9RkEmV4MO0ds6D5PnDW0K9TiJJ
            9Mqkte5wJQGvNxK4wAAIsLPJL+rggcst+Cvt4Je1BDx2khebGuDR/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T06:15:14Z"
    mac: ENC[AES256_GCM,data:aKz/7Ri68Nb1sjC4s45KeG2D2rxyaV5bD4Yr4fKR9p79QTIvGxIkTDHKufIlJ5buN07GGf0akj6Wm4V+m10K6k84cRtUPwIoYtTbb8SjSW+P0roaiWZ3MJmea+cnLOjYdDRO7n9wu2QHyDwMx/dbT6CSZD1Tx9gHQMbn4GSiRqg=,iv:t7RS1CzEIaRCAShOg7QswfOeCwwaIOGkPx/VhMzvLEM=,tag:yqd2udzLB9KF7pTVw1mgxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
