apiVersion: v1
kind: ConfigMap
metadata:
  name: overseerr-health-check
data:
  health_check.sh: |
    #!/bin/sh
    response=$(wget --spider -S http://localhost/api/v1/status 2>&1 | grep "HTTP/" | awk '{print $2}')
    if [ "$response" != "200" ]; then
      echo "Health check failed - HTTP status $response"
      exit 1
    fi
