---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app transmission
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
    - name: vpn-gateway
      namespace: network
  values:
    defaultPodOptions:
      annotations:
        setGateway: "true"
    controllers:
      transmission:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/transmission
              tag: "4.0.6"
            env:
              TZ: "America/Denver"
              TRANSMISSION__BLOCKLIST_URL: "https://mirror.codebucket.de/transmission/blocklist.p2p.gz"
              TRANSMISSION_RPC_PASSWORD: "${SECRET_TRANSMISSION_RPC_PASSWORD}"
              TRANSMISSION__DOWNLOAD_DIR: "/media/Downloads"
              TRANSMISSION__INCOMPLETE_DIR_ENABLED: false
              TRANSMISSION__RPC_PORT: &port 9091
              TRANSMISSION__PEER_PORT: &peerport 27071
              TRANSMISSION__RATIO_LIMIT_ENABLED: true
              TRANSMISSION__RATIO_LIMIT: 3
              TRANSMISSION__SPEED_LIMIT_UP_ENABLED: true
              TRANSMISSION__SPEED_LIMIT_UP: 1500
              TRANSMISSION__MESSAGE_LEVEL: 3
              # For changing webui
              # TRANSMISSION_WEB_HOME: "/app/web"
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
              startup: *probes
            resources:
              requests:
                cpu: 100m
                memory: 1500Mi
              limits:
                memory: 6Gi
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        nameOverride: *app
        ports:
          http:
            port: *port
      bittorrent-tcp:
        controller: *app
        type: ClusterIP
        ports:
          bittorrent-tcp:
            enabled: true
            port: 27071
            protocol: TCP
            targetPort: 27071
      utptcp:
        controller: *app
        type: ClusterIP
        ports:
          utptcp:
            enabled: true
            port: &UTP_PORT 51413
            protocol: TCP
            targetPort: *UTP_PORT
      utpudp:
        enabled: false
        controller: main
        type: ClusterIP
        ports:
          utptcp:
            enabled: true
            port: *UTP_PORT
            protocol: UDP
            targetPort: *UTP_PORT
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/name: Transmission
          gethomepage.dev/icon: transmission.svg
          gethomepage.dev/description: Torrent Download
          # gethomepage.dev/widget.type: transmission
          # gethomepage.dev/widget.url: http://transmission.media.svc
          # gethomepage.dev/widget.rpcUrl: /transmission/
          # gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_TRANSMISSION_USERNAME}}"
          # gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_TRANSMISSION_PASSWORD}}"
        hosts:
          - host: &host transmission.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: transmission
      media:
        type: nfs
        server: "${NAS_ADDR:-0.0.0.0}"
        path: /volume2/Media
        advancedMounts:
          transmission:
            app:
              - path: /media
                readOnly: false
              - path: /downloads
                readOnly: false
                subPath: Downloads
