---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./homepage/ks.yaml
  - ./discord-template-notifier/ks.yaml
  - ./pictshare/ks.yaml
  - ./open-webui/ks.yaml
