---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - ../../../../templates/volsync
  - configmap.yaml
namespace: ${NAMESPACE}
configMapGenerator:
  - name: reverse-symlink-radarr
    files:
      - "reverse-symlink.sh"
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
