---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mymindinai-nfs-dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: mymindinai-nfs-dev
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "wanshitong.${SECRET_DOMAIN}"
    path: /volume11/MyMindInAI/images-dev
  mountOptions:
    - nconnect=8
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mymindinai-images-nfs
  namespace: mymindinai-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mymindinai-nfs-dev
  resources:
    requests:
      storage: 10Gi
