---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- secret.sops.yaml
- images-nfs.yaml
- configmap.yaml

namespace: mymindinai-dev

patchesStrategicMerge:
- patch-deploy.yaml
