---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  template:
    spec:
      replicas: 0
      containers:
      - name: discord-bot
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: discordbot-config
              key: LOG_LEVEL
        - name: EMOJI_STRING
          valueFrom:
            configMapKeyRef:
              name: discordbot-config
              key: EMOJI_STRING
