---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: discord-bot
        image: jgilfoil/mymindinai-discordbot:v1.1.0
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: discordbot-config
              key: LOG_LEVEL
        - name: EMOJI_STRING
          valueFrom:
            configMapKeyRef:
              name: discordbot-config
              key: EMOJI_STRING
        - name: SREF_REACT
          valueFrom:
            configMapKeyRef:
              name: discordbot-config
              key: SREF_REACT
