apiVersion: v1
kind: Secret
metadata:
    name: discordbot-secrets
    namespace: mymindinai-dev
type: Opaque
data:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:cHBOaSlNNulqNcJUndvABypOGcL6YQ8asFNy2lic62bvQf/riYbQJM6kdVIK3bKmVZ5To5tqRFneumWOZJ70Kh3hVg9oidutec8vkulNh6fW/emXX5XSj8rds3QN7mj6eSfQ0A==,iv:UJicKVLdltDBqufCHCp/1C+/BoRfPO4Fa/NwwrZofXs=,tag:cxHz56tluAO41P8/u7OgKw==,type:str]
    MIDJOURNEY_BOT_ID: ENC[AES256_GCM,data:KqCsN3h8VFsYUroevF+wyaScCwbO2qwxJghySQ==,iv:vuX5/drmkBu9I1WeupKcZTRMv+nOG+2RQtrBUT5bSoI=,tag:Qt92EZLXcVkmbSFQg3BDkw==,type:str]
    AWS_S3_BUCKET_NAME: ENC[AES256_GCM,data:Iw29bXnxPvpDif0mWN/ZwPYn4t9bO/buJn1ViCuTmzVhL1kn31DUpd5J4AxYqX4ninc8sMnah0B496we,iv:26+F2HP9WH7u/f9Vx4H4qbMbyq+MaYAvyqV3St1brhc=,tag:KcWtif1t9DxussejwZbUfw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3IixIjfNT8dO9qrgilyp375VlXJxlr8wepe5MA==,iv:jbApVWfVLyFGOYNs75T7WIhz5bGIWZDcwXxqkXM+5TY=,tag:fhyq0ss1epiGMonYpLd3RQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6HnsP11pmfxzPbeYHtyht13t12f2/Q2IwVdSup9AUE5iaFbWYICzZkJn4DCWIVBWvy7xWa+NdjI=,iv:upRLz8HFjKOAKlGba2v73vjgeIPBPInc71xZHS00cjg=,tag:YtYmktK6N2AUmjW7rlWvCA==,type:str]
    AWS_SQS_QUEUE_URL: ENC[AES256_GCM,data:Cl6Et3nurF8FMMamE/XRH//5SFGi6XMZNip7/ooc7UN2eH2QygM/Usthxj/dkAdxnz6mAqBXjW3l4Ekt3RuVO8crsCOutGZTSg==,iv:gCgiNIE7zr6RC21/G3UjBhd0En3mNp1SsyWXnoY/Tf4=,tag:rKI+JbAgT64yOEX4wXDLjQ==,type:str]
stringData:
    DISCORD_DL_CHANNEL_ID: ENC[AES256_GCM,data:/az5j0z75V4rf1jr/0R78bQCGA==,iv:z7D3GzrdDIsS9tQgZFK5K10HqyolDCmRBitekiQg8nM=,tag:yOd3PQ71HATglLi1wDopFQ==,type:str]
sops:
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb3FjTTNsMFdldWk2TkFX
            SVlkSUprWGpRRWRhekx1cjkxZGlYMDdkcVJNClFLNFBjS2QvaG5rUnJvU0NOV1hQ
            VXpDL1JnSVhZUkdqK0FOc3hiVU9pTzAKLS0tIFc1ODdveUVUaDNIZ0lIT01ORkVO
            b2NPNldlcmViaWpudzkwL1VhOXNjTHcKNsUBa1CpWyxqh+zUT1/Fv80NuZ06CLNr
            3zRxWLGsD6wyxJbnGaxfu6YnUjruj5W38oVlLLIHGhDoBIYfVKjRiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T16:31:22Z"
    mac: ENC[AES256_GCM,data:B+VA5DV6apEZFmxGGn8QwlxVNyLAIZQb71S3t5g3PlcAjkSkWG236a89TlpqNOO6i9YHClmke+Iujd+2LhjPNyOgPNsdEaVrOJxiOW9NxbvHkCdfP7kcU3lNJ9o6+jTwRhQott4QlX/xYkcrHxJVxqZnoKlxZr9Y0doyngU7hi0=,iv:H1vp6MKGQeaXR6sTv1L0FUB4N2MztzDz1NUk5THYYQs=,tag:wK7LqUXwxF7IMdVLRtOFaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
