apiVersion: v1
kind: Secret
metadata:
    name: discordbot-secrets
    namespace: mymindinai-dev
type: Opaque
data:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:vOF1LEzWwQS9dRYz3QGJ4yV88W1fBJtN/KXEzQo1BcpJYxibxPxk7okrLV6xy9neLCAtaJ+rm36WqVEcFKSvKDxS8CNGGFNSjcVdkdyG+C9dPC0C74He34sxqIaes9K5uA8SZg==,iv:1TBdomYUDxvgWQwQS3rpawONYI28lXx1llyHv7gCWMk=,tag:JUcyJVYydaNzl5neLn1LWg==,type:str]
    MIDJOURNEY_BOT_ID: ENC[AES256_GCM,data:mzBsMfcb7YZrwegcYOr79+UgQcLmhcu9VbWF0Q==,iv:JDL+Ggli3NPfBs/4IWQjsVmemMhFGwuloiGymwzIPgs=,tag:/ExkBIKkI469/9BIkksoHQ==,type:str]
    AWS_S3_BUCKET_NAME: ENC[AES256_GCM,data:3GGvmSnGAP5z6ZCeGa9p8DchNacCWhWCXYjqmdQYyv7Xiy10Sfh+UXJK9o6tDkT+UTZ4N56aNHNNEqLt,iv:atYkcsRPNKR3ztaQScHYXYLQYVhPaLUWb9OkhtL9SyI=,tag:42FSGiLNyXBSFnPb1Du9FA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:N0vBXt73xv/z3TtGcfs2xNOdU8c3iXx2dJCCpg==,iv:+dBdRFZGJ97MfdCUXa5toL45XABffmpYM0RKcaBcFx0=,tag:herSBD7rcdu0sdv4mygpHQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iiVbDb0/Kgj6gLhA05poIFYYvUO42x5bt2pfw4wG7EN9ZCGBUT8OaXFCsGeU5kGVh1Tg4P1a2vE=,iv:mWZKVAEM1ZuHlc8nOf5kWD9zOAop2ypglIwMenJCw4k=,tag:NBiYwSOjsVg81XGUn4M5Jg==,type:str]
    AWS_SQS_QUEUE_URL: ENC[AES256_GCM,data:QK0wGJPX3XtMgl6zVlbnqi1OskT9FEUdshz/l5PkJyxg4NusDvnDhVy4MsNfUQOMhd91TR1Q3rfIl/azgomIIPqUrvxkzIfKwA==,iv:0CNHzJZ011IVst8I93x2pzEEXxkzwqO3MWEslP326XI=,tag:tD/0N7JFA4xFbEZEpiL8KQ==,type:str]
    DISCORD_DL_CHANNEL_ID: ENC[AES256_GCM,data:ovqDrSd3htQ5Cq5X/UaKKYZT6g==,iv:XZkIpYwFej5Cg5DL55caCbmn4JLg75Oqrn1xP7UholA=,tag:t5LSln1IkigjFk9tIvnc5A==,type:int]
sops:
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmM2ZaSi9YZXA0Y0FOQm1V
            OU13K2xMYWtwQlNZUTVPOWxFWmEvRkdQTm1VCjZRNEdqWThBSkxHTnhwMHF1RmY0
            NlR0NUx1Mm9McDNPTmFCekNHRVJIbzAKLS0tIDlrRnRDNWd5T0JORWpDdEY0aUVJ
            ZGp5TzFKS2JkeXFRZjlzYlBBM1lReWMKmfbwuH4FAtYR3T1oLgX753CW2HKosNar
            2Yq7qFdX4nZwdcA2qebme4vXbGs3WLqBkyOAwDXgNQdLzkX5rBqplw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T15:46:50Z"
    mac: ENC[AES256_GCM,data:83FxQkR06LJ1LyojzDiLeBG3FWHnJSsp/qtgTS3+Aak3nbcocrRjcWofDsuyQl6n/Qft//FoWZ5combJ3mofBsMwKDFHbd9EKB46wA4RB55+7KDDNWBzNGybgQu9Qr0vI76dPC39c2KaIbzHcNF+e3XWa9y0B0MpTkWWESQp/qg=,iv:QusO+Oov10mbyGeuSdU6VnAzKuhj1ToCcf48xtSnx3A=,tag:VCU8MjeH67b+AJA4fhDUEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
