apiVersion: v1
kind: Secret
metadata:
    name: ghcr-login-secret
    namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:d+pvZ8YR212fAnFVDLg0iBsgKXpDA5/7Ulpt1TOPqKP9nhK4jlnJOrd2ENjNIWFPHM6gvFmTELEcNG3XWKXthc7kxvvxMs6keKmmi2Wx7I/4nGE7Vwr5YqzzBjAg6r1TEWu6YjLkH7U8poLpbco7FEUgtCFSSBZu7qvwyqjuPVOxXj92X9ZcTQkqcaWHkUhCGUCjVTvvb1aCDocPrTSk,iv:W4CS7MR3Zt5WyiQbeML5lug+W5Axo9oDIy76YL8/SKw=,tag:2eo31HLsWe3ONmZ1zR7bZg==,type:str]
sops:
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSUlNZkNHeHkvbWZUNXdB
            WWxSMTlOeGJ6LzFNc0dMcnhaWC9PZHAybWo4ClVkMU5FMFFyWW9TVjB2RlUzci80
            d2gxS2JseWN1K2o5MkhlUEhoajFrZW8KLS0tIDNIWXJjdStXTXZ3V1k2OEJpNHFi
            TG1PbGphZjJ3eHlJS2phVjh1Ykp4NjQKEv3iAeSql+XXusIVsZglyREUm8SRu7xM
            ZRb0s+VO1OuCLUvY1EPgmqVFIxIdg2u555SK9rt76DJ/EfiybiV66Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T21:00:16Z"
    mac: ENC[AES256_GCM,data:QTJZmyRu5mUl+Vqjuhd7keqJhHIx2Rs9qOY+/oHT9H3+BuciBGEGB+gHikNZrxKxFzOZX/cnMxYYhHjwFWcRdF+AqWfeExCRKVivEKdbIWHh8wFFelerE/63+gwpY/QapWbbQNtrDkc5oP22HHZDC/19CwLaotlXDlUkmUPjmog=,iv:vGH6oVG3nlXf6KeWM/k9waN289DQVPZDeu1fN/pcadI=,tag:DE2n/y170gsGT/L3S7kwcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
