apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:m0VMaivxsZhOi6s=,iv:koiCmy5HBx+Yg+uViFjD+yU49k1sQmCtXM7zhRZPIdg=,tag:5rMVKJLsJR/7u6FRzsH4AQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:zQM8bVo1W5R2aOqcvbR1dMIK,iv:7MAfC9sUOOSpYDUqLgRGAAJyLQY9GD6jFTISdrEi9bY=,tag:7ZECnHe2o3/TeZLbMPXkcg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:hibGipAXnNbLxUVAJdmr7f3Xk8Ndcla4B6dipgPffycW81mM,iv:xjYABnZ7b+cOQ7vtQPya3yUgAhZ1MSKHFUweOfIKrRc=,tag:2sbseXz715lND2JuVxslPw==,type:str]
    RESTIC_REPOSITORY_URL: ENC[AES256_GCM,data:CLru/hRZMy+7QpTHYt4LaJGqhCEI3LLVbBFJuGcdvEFQ/uAc7ubKGSwpy2/g0g==,iv:GYwW8/8ijHoDbqrrIZxfxzMtKDPLuxxDyz7ZijjMo4c=,tag:PP577CUPd2So+IrV0kbmoQ==,type:str]
    RESTIC_REPOSITORY_ENCRYPTION_KEY: ENC[AES256_GCM,data:+kl440gtAsqjKQPQ/Uu9ZA==,iv:5mgnAVfBd+Kd4Rum7V83VirhYey9yBra3bcP86HxWGs=,tag:X5/SvDYk3EyAO7YHnaREDg==,type:str]
    RESTIC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EGzEWyVMwdcoUGTLaRhTKQ==,iv:C1fRuUsZ6wu6tdMA6Uc8QD2Pts+X/ySBxK2nU6Mip3U=,tag:Nd17R2aQYkiH7qAG0CHO+w==,type:str]
    RESTIC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vG0zyOeJlNwMBYIpYPNULZltHos0n7pSP9TKjAFPmlE=,iv:SZrxQt0/rIG2/Um5olpgHIWe+bOQ1Eacza24l8SVFQw=,tag:UO+5RCBbvcB3KwYjtckNHA==,type:str]
    SECRET_VPN_GATEWAY_PORT: ENC[AES256_GCM,data:tc+t7Q==,iv:xRRwxEc33q9r6YMllXXN9J7XxWxCftoK/yf1HzloQME=,tag:sWYe8azuF7tbcoKlqDO7kw==,type:str]
    SECRET_TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:VlHlO35ksvuvXrVQUKCCSA==,iv:ZpjlqmObnPOuVWIl4gF922PLBPn9du4pHma0qAIwJzg=,tag:IecRO+zrvaIfD+fvpvf1Mw==,type:str]
    NAS_ADDR: ENC[AES256_GCM,data:heeqopJ8HSgkOlwO,iv:Q+bRwuJSPi8j3Wfz5Ac+JBAg7htdv37DAWNIDZjXiM4=,tag:MAFVAVz1jRhA/7XfIyP3Ig==,type:str]
    PRIMARY_DNS: ENC[AES256_GCM,data:OmeYaMh44HFpQlynXw==,iv:jrkh+9CwU3AxNlWsuixL4Rbm/kLwOGA5y8PUEb/+1OA=,tag:5U5Q3IIANSOaNxW8trv1SQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQXdpZXRhNW9Lb0dGdmR6
            MXAxU0lGa1NzQkhrRUJ3YURSMXRmdDExbFJ3CndRY2hHMnZzZ2V5bk1YYjlkOFNI
            MlB4MUVWNXZPSzJnQzMvYm14dTVTUDgKLS0tIDIzUElnNi80YW9rVlR2clVFY3U5
            NndsMHYwalFUMEs0Y0JhMFo2MEkwbXMKv0xXclQ/C6AMs4SblSyP+vSYpZSfJgmy
            I60J8Bbs33VgfCBuHQz+RvXoczMhRXaQJxdpsBz8N0y1C4N5mBqnbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T23:32:15Z"
    mac: ENC[AES256_GCM,data:CNeJ8XXpXl1TrvRLWkvaFralyLlerwKM/aDfwIh/qa0XCuHbAjvIm0in18HqWB6g4cS56t+enkpPGYsYE6CmwHTxxtCfGsDFb5esV/n1uEW56ot8b/0jYktiXp0AS6RZFhzQqJ63XgOwKObXFHjTKo/frkph1dU1u6sAHGCobDw=,iv:o5ERWLxYbpgLJdAE/f3PbA4Ui5f0yvzLJljuNgV4gWE=,tag:rinMOMjbON3vqAC/iCITTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
