apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:t2RrxjaF0GkcOWg=,iv:nFjBZb/daIWwZqRJlnHapto/bJIKGAfUEFsqmC3S/1A=,tag:XUE0jD1KwwCatH3AUwWzHQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:vnsuFOhWefizFjwHbX9g0oRE,iv:B+xfyUwVu9D+w+OOfOVpWz3v2/Vq+0IsGmJn9PiuKRc=,tag:8/0WefJKFytz9hJfG5HoXA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xeJXvBAGLYmf+Z8gDLmiT9aQHOqhAv3B7mUyKpef3YmZkU7Q,iv:yFPT+7G3lL9sw2d234qQmKPWi8WYIefNwCiFSVnZBLA=,tag:PpzCx2WWxdVhxVl4j5Tuag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdlQ5bDUxTGhjRmN6SjFN
            UGg0VWNTNkRLTUxLWG9rMFozaXZEMHJHbkdFClJ1VDl5RjJTbnltMnZ4dkdwYWIz
            dkpqS1hTR1ozL1pUaG9RaEt0V01kSzgKLS0tIDFRejVLWkY3YmQ4ZlFWOUphYm5G
            b0dpbzROSEN0ZlM0cXVlUllVVS9zTW8K80nu+/cKdaIvPx4W0BDb1vUm0CxmA6fb
            S7DxRXPn8nlmX/yx8e83Wbcgkt6ALylTkNksXmklMOk0lcYa8NVliw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T23:25:41Z"
    mac: ENC[AES256_GCM,data:jEdb0eVHQMhnbfZhkTZOzYhH1dO8ahg6+dgn3P7ldHKgeevdQYyuA+pZK7KIIVBhnW6BxrZadhROh7fMiyC5XnLfSqxa4X7Ba5jTDaUoqxFaJYCIqrcVaXmnMmOMDNVEsVf/m2fguv5cmHow4yJWaSGQMBTLBlYiRjll1qdXe3k=,iv:XHZA5NDzjEKXahQ7L3GI4AzBBA02QE6d4ddCRdmS3nY=,tag:VRVj+4dUkndqJ9e6ixQ2Qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
