apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:p/s8txkV6RxrHNU=,iv:gWfjjMZ3GUc2Dj7jSdnagqAqTnO7r6bp5269KSimEVc=,tag:dkjvsu9AUR5Ri8pXc3Louw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:3MTyDVF0h+H7eQ7QWpVEF+wx,iv:SmLAv7AmX7j1rDFz9Cjw7m6EjCspPd1Pxl/znZ/MfpI=,tag:WjYYt5QZzgKcyBfUv+0PxQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:SwP7drIJ0hLU27AFwL2CEKL0YA+HNyubGDKcPAbuQhZJgJzE,iv:L/pXcA23zeZYSHJzh4Dif0YhZee4LrhXQurBsU33H68=,tag:dt3+Ds2MnKrY7VNETAPJLw==,type:str]
    RESTIC_REPOSITORY_URL: ENC[AES256_GCM,data:O3Wa97dWAO9YQgYdHpNJTDrty8mTLPdQnTNGKIE55bdAF93tKaEbRtS/nKDwyw==,iv:/0shF4k5VLKy8P6uqcJ3jakNJ+u+n0y/6LmdWRgK654=,tag:DAmEuvLTmnaIjRHGO3QpzA==,type:str]
    RESTIC_REPOSITORY_ENCRYPTION_KEY: ENC[AES256_GCM,data:J9UeIBcdWBj7l8ZXeHwUsw==,iv:QNnilY7B3Wxq4z95l5AyV3PRv5dqNPde2v/Z8cRf+Nk=,tag:o0qRbdJb5QVR5kjZ/6IDBg==,type:str]
    RESTIC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lUV2DXFxAB79zGdwjCjxFw==,iv:eRiFdU13mIONR4MPQ7rwYqRRhc93pIdbXvFhql6RMyk=,tag:i/Dfr0igH3Bgma3Jb2oQYA==,type:str]
    RESTIC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Dr8ZvQaqcu0s7cxzhMdHtyGqKeUvN7SWdwuaDlPFySc=,iv:W4VoF8grKK//O23flok1Go6X0s6Q5DzjVj0kID5kRh4=,tag:D3rtCsPRJ+5HCiWtTLf1Vw==,type:str]
    SECRET_VPN_GATEWAY_PORT: ENC[AES256_GCM,data:awc1Og==,iv:W15lMFkrNeFcNIhHNjJnidjUVuxM0PHSxmQiSWg2OKY=,tag:bCUPSZ1GA16K2G+qbaDuNA==,type:str]
    SECRET_TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:Ys5NHp1hnisxUxQf9ooipQ==,iv:JvQ9l2TNSjyIFCW79eQdm0sWzR7Nrv6vYI3R98vNJ2k=,tag:uiKgZbexcLtDRbIU0szVTg==,type:str]
    NAS_ADDR: ENC[AES256_GCM,data:J2HZwTh/QxZS9izg,iv:jzPp1/6DFWc6N9lTuBfYD91+eZT0Owa5hHbc3Zd1tnI=,tag:DZBcUWxizaYuqt5idRIyvg==,type:str]
    PRIMARY_DNS: ENC[AES256_GCM,data:fV0yhiYA7z0qTr22jA==,iv:oExAx73rglZH6DZaWgemFlIzXKWKJXbRZXMfhmPjnb0=,tag:lVog6ZIqDh58BHv6odIlBg==,type:str]
    MINIO_BEARER_TOKEN: ENC[AES256_GCM,data:4d2Eme9nvPVnS8lUqq+ayMWqw44DtBPIOKmAnsj2hqdBTr3UDBKHwyPssG2aXj5iyRB4e4+m0xiJ7Lv+vP697Qhc3y3ez7ztcZccij7HWY0Q/V8VkN/vnBa/nQANoLyqiK9kIAa5q3fJLgzUck8KfYI0CmgreSdHjqfLO38OSVAIuMgoZO5PitORBeYW1Btma193Byjm330quXEPMjrc/meZXbukf+Upv0eV7kJ71IQqyNaBoZmtQ+PIERjE1MCYJplvud+0J+o=,iv:U0poJPiErh/M0WlSNgTbwja2mR9Qu9TgtaSJn64t74U=,tag:K0SZBZOFWc1P3/55mbvunQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwam5ZakdqYzRNdERoOGsv
            NU9hVkVSemdZcUJxSTJnSTBMMnBFTFFPR3dRCkhmaWx2Szl5S2NlemJYZUJOSFhr
            cVp6UXIxRFJQT1BSZFhTY2ZpNE9CSDgKLS0tIGRwZ1hTRVo5QTRwcTZiYzRQSXB5
            dUpZamt5OHhCU1VPYzc3R3o0d1lhM28KAgOCrIlhXIhfngdRbUAeYIBY/5iaHLiV
            Lyskuun587OvSj75t8A8NM+5G5QL7W5rwH6rERozKzIGUz4y53slRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-22T02:49:42Z"
    mac: ENC[AES256_GCM,data:gyHvhxUFEtA1847iteXJUPhqlJO5Ja/l2bASfT8RCJ0BXHJJe3iYBF57ieTYq1L4m7Xs5HefPuzugLS8y6s9zjGY/EO4idYwNSBBSvlGsoNGA6NklYyUGmV/O6j2iwUdwXbNsUef6VmLCyvYven6e4VIpaUrdBon6SlQ9noFIWw=,iv:3Cxo272kr8oAJQnzBE0repbp/vl5mID+OO/FzBtFCwc=,tag:ujY14P8IjRC2Ksnh31WU/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
