apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jgleOlw0Khb6aWc=,iv:eCZ2i+E12+rJLsfRT1F/yJeUjeLEj1UZD7FJr+ngyXg=,tag:ABJY9a0rYeP88uyGHtomlA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:zJZ2vh7+4jn1l06osTE53c9A,iv:HPzbbLeyuNOZ0In+DVhWhfkHTouzhwiA9UZGyCHtGBs=,tag:viLROfXkXNpxJyxNmnARQA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:i71jRxwRhJzHAhJvqJwml78DAK/+uaTvwoTWssS+2RyKzVfQ,iv:DxrzeObxUR+yncHkBu7gc/zwVYN6g4XArMVE54UNYdE=,tag:eU8FmUPkbfjspwBykMZHGw==,type:str]
    RESTIC_REPOSITORY_URL: ENC[AES256_GCM,data:vj6AkiUcw/KD7JjoRl0V3JQic011+LCkx4sAsqg+9KB70TUyiZpG13FbVnEnTA==,iv:4z7+oGLDydZBtM8ZGqdGpyjA6MHxdDmlxsdbaNUKUk8=,tag:DxepENQLJ0NBZjN/YVkC4w==,type:str]
    RESTIC_REPOSITORY_ENCRYPTION_KEY: ENC[AES256_GCM,data:txNpbHJarWyFXH9fvc1xWA==,iv:XVnAqM4SluA7TuYwi7xilBXERJw21Bkg3+eRDs6Fn/E=,tag:4uwoiL+fcG/PltkA8IXcpw==,type:str]
    RESTIC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RPKb1Drkb97NMqOFppZPoA==,iv:TeAaF9EFtEqcibbRwUM+QYsnwe9PIfnu0QGjaciIUcs=,tag:0IQxvdUqLI9Bp6eWdeiWZQ==,type:str]
    RESTIC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:D+sYfAbNykq5G2QGLa63kaWDd9yq3wlXQ90iIY7zDGE=,iv:jm8WjvrmRX0J5yoFm5Vcu0u803GlERqTeaIzqXXB25g=,tag:DTkQE3ZrYJUC1Cqx/4aGow==,type:str]
    SECRET_VPN_GATEWAY_PORT: ENC[AES256_GCM,data:4M4eOA==,iv:9IAXOMxlXypL0h4ed75cXobcFedohHgHO+2rjzbMEws=,tag:xChF7bvGcMfJvwMGLcMytA==,type:str]
    NAS_ADDR: ENC[AES256_GCM,data:qTRD0mi9VR370Ajr,iv:/0AQaLyhnja80U84Rzxl4ekNWaPMF4UDP54LJiy/FHU=,tag:mwhF9WzdghP10fmxTPoo9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTXpzMFpEWGVESklkbnFr
            emNDcDBLNnp6MlFObU5SK0FHZ21KSVRQZGtjCmh2RWdRMkJ0bEdCZ0VmcW9mUith
            Nml1ekhwWW81MC81WGJZVlJsNE9nVWcKLS0tIHUrSEM4SXJDNkFkYzJmYU1YNi9B
            Y3llMUZRSjNyaHo4TW9vQjRseGNBQ2MKYCaDXMeThtTkanQJCNyRwiTICBPcb/yo
            kBwldHA3Cv12ji0XjUBxGdotPF5LfRD/dAMLmTavDGR/Ns89mLvhSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T05:10:57Z"
    mac: ENC[AES256_GCM,data:edkDfNwJNaKbvgyuQJNtRZ9XAyWoR80xXfKYsvntdexwROAVbW1dxBiMdidEiCnjCvY+FzD86LTzBYI6q1bmPgpM78dOZnZIGa4WV/Wvu3khUFi/HDAMljB2S4YurOpzkGy1AkYFvHuxEGj6/Mup5iuDqIRHY8f62nsZlN+dnCc=,iv:3ofG0v7c2AjLkO702lLpDu4PIpkVEGA1lJowjzssNJo=,tag:XfHUAuPM8KEN6YF523X/CQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
