apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:SjK3zgPTf9yjQCk=,iv:JORcHQVfHRYDArs03jxRvhDMlCNyr5CKdJPwNGMPgWo=,tag:QIBW/ucTLjy64RxIWKXNWg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:U7j/FU9/PKRwWrWeAAJab/If,iv:daLkOhWYnlad5uFAo10KLw1de50aRAoSTAlac86a8gk=,tag:ZVh+0/RgT09ArA9d9IzGxA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:uh3y5lMk6NM0RlEtb4oRD1u8h4/g0rW1vIF37inmhjH+OPD9,iv:jq+m+SP4PWFqfPWFR6+RAu2ZvwOM/peNXquip5Rj36o=,tag:cncILZcASI1KZ1pK71Zz4g==,type:str]
    RESTIC_REPOSITORY_URL: ENC[AES256_GCM,data:tSVqRRKwtGKdx5WpFCtOw39JjqiXClAGPTEELiSyGYOgt4cIamsU1S8ZqDceqA==,iv:wxUsNX6SO8YDVgYAacqh3aH65//W1MG0gyKD1IexCWg=,tag:0wewVv1kSpVWDRS7pyJ4pg==,type:str]
    RESTIC_REPOSITORY_ENCRYPTION_KEY: ENC[AES256_GCM,data:P+FO2+zA7YtVlgyPohLemQ==,iv:JNofNCje6M/HyjQwQ5FfsAytdqHjRAk2gOsBzG+tpok=,tag:tooY/7OTjaVYVuPt5utKFA==,type:str]
    RESTIC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XRLAFfcG3j9R7bQNcgOOnA==,iv:EMioVxBMqm5Y+TlXmsfh2pIQ8G6aHqg8ooi4zF+Yhh4=,tag:GdkmJRQbHWoh7iFAt1dGuA==,type:str]
    RESTIC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:N0MGTOOlAKw4F5uiFrAExwb8lZE6dhsIcCS8TI+gKdk=,iv:ouXD4kwArfJqmE6Bs1bVAzuftBsUPQYQW19jh9NjZGk=,tag:PYGO/Tu0FEYvm0feCfL3QQ==,type:str]
    SECRET_VPN_GATEWAY_PORT: ENC[AES256_GCM,data:FK0/rA==,iv:3ltWonDQBayPoZa8AEX7rSmu4eiKB2NafQDH3q2VOr0=,tag:jyAYruBVZghuvQAxyTm/Dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQno1MSs3U0hoUVVNSlF0
            OEdrWXk1dHJMRFNKYjhZL3pWS1NucmJFejBJCk55U1JDUGhQa3o4d2ZFZnRHa3NV
            K1BqU3JzSTZIYUhJM2FXa281bUVJZ1UKLS0tIFk2bndISjV0b1NsWFJpbUN0Tmcy
            OWhHOUNhR3FRaXRZelNWMkZ1TFdoUm8KN/ZQTQcuG05XUf235s2Vni2daqssOT0O
            OB/+zBDDtnuVbSDyoRYzC5sSSpkJ8ld/H0z2Wk+3yPD3FCUpjh6yUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T07:58:58Z"
    mac: ENC[AES256_GCM,data:yT/56miUrKsl47loBG9pGUo//eXSnpHMkCzPtgMg8k1L2RzW/KsKien4FTTupU8poAuUqBs1WDEDdbmd6Wb/STcOS9TdNxJPCFBMZ1mVopPKT6YjFy4R9ob0NUKiYPwQmtKiX+0no0uCQ0tVvCTyLwE7B1MsN834UoQOAPBcGrE=,iv:pUA9R/RaJhHtBnsvOI6rghEg6LM35obo9D4tCdbS37U=,tag:hQLca3B1nMEft3qPTbdltA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
