---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-cache
  labels:
    app.kubernetes.io/name: "plex"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-block
