apiVersion: v1
kind: Secret
metadata:
    name: external-dns-local-secret
stringData:
    EXTERNAL_DNS_RFC2136_TSIG_SECRET: ENC[AES256_GCM,data:SpqjR27jNXk6GH9PQn4ZCTaisaSnAuFl+xug3xZQCfy0BLAHxtG2pA==,iv:T4i7Ne0ZbdsHNEyBDJU2HUXoUUcL+E4ClXW9+PJG9CU=,tag:v8ohEmIxoOfjEvyWEv+XUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV011ZEhCcTllSVplVHF4
            bHY4Nk56M0NNSW1YRG1ZOVZqNWlMYzF0dDNNCmwyVmhqRG00R3kzTzhpYnIwdzJm
            K3d4L2NtQ3dYSGYxOFlaZGl0L2xvZzAKLS0tIHV6T2FpK3RiYVY5QnRNczJlVzZl
            S1phbnJMYURsZmtybFpSL0VvSmZ0cE0KYQ4JRUNzA5tOytzbXDgVjlhGF7MoedpT
            WzyS03MboVdbvL1alzoooRHFPEFBtP5h1oW3MMgm6cjbzaS0RXMSPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T23:58:20Z"
    mac: ENC[AES256_GCM,data:VRu6gzvOnX32CfhwOLKrYPRCN4liYvHFn6Scn4+0vu7CF/atYJITV0HmKbvZfw3JMREbM2BCDaSzKbbg8HqjH0606N5kno+S0qrXpd8cmZiqJCuC5lpJpW7JnZyghzdn3Jc4BSgjhRKQi64T75bSxpZzweZQ+peGv97m503SRFQ=,iv:j7jZVABroq2C0HlVPSH3bXMSNOr1QwgrEtEc4U/Un1U=,tag:MHoEDqxfVLiDafS802qUVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
