apiVersion: v1
kind: Secret
metadata:
    name: pg-backup-creds
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:C1tap+YjxSrq7SRTb6hADR36zWY=,iv:7sgVGE+CTteUVvrTIrBGuzsvn2gVYOFnN19VzGz5zow=,tag:fFK/rBU0sZl7kyRQvjANEg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:1xmoBPTBZmleEgqWZpZ1auhOaxSoFFCHQX8XCN6YHAsDS2WQO1+T6A==,iv:D8Do4PWRWKziDr6wAPc9ffl6xZqrcU8dkvgPvA0KrDw=,tag:Vx05DE7RoEwKZX0PMxOn0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMUs5RmEyMTd3a3p4bVg1
            MWM1K21uaEtvelpvdHJHT2tUUStNYnlvc3gwCnBzd1lZakFlTm1hek9GWGFqVXpO
            VzNqRkZ4WVZMUStRazdRMmRKeEtSY1EKLS0tIDhNRHJzdGZueDJKNlEvVG8ycThy
            cUFCQmgwQXJhQmlKL3NGbkNJakYvS2sKD/sjI24MJs2Q0UXtv8UXzDkwQDVQ4h/L
            kpNaU+fyo4MWa1Vb0YNnjurLuK/4VCN97J1cVmA2KaqUELNI4PHnDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-31T03:45:23Z"
    mac: ENC[AES256_GCM,data:uh+4yHWiO2D4Nny5CYBNYeAwuOXSlyFPKatOQqWMuJ1Mpaiqa9Smv6cGFRZB9YeZaBgblfbvIylL5517RVCU1XfKwXkBXk7UAOmRW9dTP3bX6xK6qWcx1JDuUPZRDcKglBTjHOK3sn+5II1RpEu0TR9e0QoiIy6GAkJVdzzU2/M=,iv:24Y1S47jB/WIDeHHq6nh8D+MWSwb/YM0o8Pd179Kvh8=,tag:u4JkSv3YRFP/1uC6lkAM+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
