---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Chatbots:
        - Perplexity:
            - icon: https://seeklogo.com/images/P/perplexity-ai-logo-13120A0AAE-seeklogo.com.png
              href: https://www.perplexity.ai/
        - ChatGPT:
            - icon: chatgpt.png
              href: https://chat.openai.com/
    - Repositories:
        - home-cluster:
            - icon: github-light.png
              href: https://github.com/jgilfoil/home-cluster
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: https://kubesearch.dev
        - flux-cluster-template:
            - icon: github-light.png
              href: https://github.com/onedr0p/flux-cluster-template
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Network:
        - Cloudflared:
            href: https://dash.cloudflare.com
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel
            widget:
              type: cloudflared
              accountid: "{{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}"
              tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}"
              key: "{{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}"
  settings.yaml: |
    title: Dashboard
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      Media:
        style: row
        columns: 3
      Network:
        style: Columns
      Observability:
        style: rows
        columns: 2
      Storage:
        style: row
        columns: 2
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: ["duckduckgo", "google"]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "I aim to misbehave."
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
