apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:FDV/HwSoWL68//dHnaH3G18Gtt/tI6aFdaNfDkoGy3Q=,iv:a1bc7gbpvtoDPIXpJmcguvCH1S7ceinL17Jcz/V9PUk=,tag:mWGKFVtoMfOgwQlMOe3ycA==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:vwphWd0ZEloyl791UJ6nX7n3qwHs5orkjkC1+1fAczxsq7uU,iv:CBvj13fM+oBCpAUNbO5Nm9nTbMyXaPjB1buydcdlyVM=,tag:DnZB+IDyqnSD2Bje3oousg==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:yxbxt76glYf0SnL0MK9dlF1GruYSHhDVN64uzY2n+xWaVKYYbYqPoA==,iv:GxvqzODL7RqkQHy0Eb7uE4hBdR731a1C9pCv3ZQBhqI=,tag:Up1HQ621sEUM7jnnaYkZyw==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:4Lj/9ho=,iv:wnz2zSHyrwKDSUEkASWk+3Ax3Av8Z3FwlNGZ+9q3b/A=,tag:T57POPUIPmeGE+hdx3U+Wg==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:WfIXS8XjRANlhYwtf8ECW6y/,iv:PthN8nmSmkm4PRuKjZhQKzLoNFa6kIyZVwXZh7ikSOs=,tag:za91bxPJ8CQIlfc26vNoUw==,type:str]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:KOJwI1OgVan+dmjHVp8Kka5dKW0=,iv:H1MRQ49dcfof4XbVBuamin1rqXnwubHetwKjTx4HDeU=,tag:k4SSNml4yAouPi7j1NvWgw==,type:str]
    HOMEPAGE_VAR_PROWLARR_TOKEN: ENC[AES256_GCM,data:uz3mka61GRJk9u5FwjB5LjDCJjofMpeT1tfcLcuTviE=,iv:Ki+PRTYr2quEG/T7/Usn1ybs+nbOKrkMtKU5+Xjpu4o=,tag:BWoC2nAQ9W3+EuojsrvfSQ==,type:str]
    HOMEPAGE_VAR_OVERSEERR_TOKEN: ENC[AES256_GCM,data:LPZvU6JV7YyQHX5nZwzaGpYddrKWnDjMjIDWQXX7XPFUMhPtU296itgbXpS5jAbHwoe4GdaaKnhdGeeXuMT8YtFYd70=,iv:5FZEcsiLQtURkwEoiVfFANWk+R3TWLSQESHo7pX5sgg=,tag:M0JBPvLq96h8L0F96XF4OA==,type:str]
    HOMEPAGE_VAR_SONARR_TOKEN: ENC[AES256_GCM,data:b5NY6vGlRFLSRT196u4u9cmCLuSOKICWYB/+8UZaX+I=,iv:Yk2swOaXMRw+sfPbkqB0eQPv0i41cdBiccsnlOJ9ygA=,tag:ORjZ2m17biFY3dGZCr128w==,type:str]
    HOMEPAGE_VAR_RADAARR_TOKEN: ENC[AES256_GCM,data:jA8X/DX5gTCl7OpHVqZ+/Bc8IDo4/3D57+cHjk05xnw=,iv:GxIq1vP01QTWYIkVzEHXKQp3ZoipNqTuFqLzOsFn8J8=,tag:urFmHkorlx9GUNHum3nxkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OXR5K3J5MzRsekJRS1lC
            QnhLQW8yajcyWVA5QnEvbnhIYTJBNG8wNkdrCkhPYkZhSUQrSGs0WU1FK3RxYjda
            cloxTE8vRGRsUTVQWXRJZDU2d3JEWTQKLS0tICt1cHQrUVRpNTZhWWV3bS9hQ0p0
            T1pHK1JRMHh4K3g4ZFZXbUJySnZvcXcKOAbaCJ/omSBV1jBX39hEWTvxaLPxmi1Q
            GbU56y7lMmDg3cQ0vvxH9V0v3S50P5m9yv6UKanFfPdOxhTeEqEHfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T03:44:45Z"
    mac: ENC[AES256_GCM,data:4DjYc/hNldUFMy6HTd17L1jW/MpreYBUPbqh/tJw8QxvwxiIPwuhlbSDKLGP9cekV2wVnSV+KA+aoeW6FZLPYLmx6pYaAKkJbqebW6yk2qUqNJcQXUq2DS/cFrBKTfdwxCiMr62ReUiAWherFsQrKG5MTjC6LGzu1llAS0NsqKI=,iv:VLv03hXTTNi9QqiP07Iaa+kgfU+gCjF4gkFkFyWGGnc=,tag:Eas1maQpsIBwk3yeGoRgYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
