apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:SLTbeM9PKnDDjPGhc0pxbTfIYf/KXHWgzHYhUcekGbk=,iv:68dnSQhY0rQEwOzSIDzxs1+euXrnrPuvHfg3zQKFRy4=,tag:/fyN+rWClhbt/tp43wE0Uw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:Qt7tQlkzY9sq9Bn7zs0SWqlkpu7h6zBXLricQB0En/cxg1jk,iv:ZxQVbYZvZMzEX+pXgSn2M/hRopKhr/1AJGKPh401ZyY=,tag:8t3NiIMEfii/Rq+dz/gstg==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:ZXVXt64+eOBPZ6n3Z69A4BKNm+WqAZOp4r2mMs1oPDjp+ydcgdDGrg==,iv:jAXQMJs5Fz06l99F9hi9V5lepH5eyenh1+6z010Sp+s=,tag:3THfUcbAmiaPSem3EUwpPg==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:d23dKE4=,iv:XuJNbfBVDz39NSuXJa1Hu5nE4FdjqftNSoMiN4Xj/ak=,tag:11LKAOacy8Yk69Yy4SHy9A==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:3dQ3o4vWHLYVH73jmTIZ/LG5,iv:hCHykY/btYGc3BH5t+eQ+JEoQvtbSwX4YuI5UxAO0DA=,tag:q2whPLTrDEJ5ixS6LLXJdQ==,type:str]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:9DreT+aDF2J+Mo9iniqME+6uk7U=,iv:UJIfpjtfCJIj5gqHBdCOkBuAoSb87tc3vlfAvn+oaTk=,tag:wG5jA4CxgwJWJqGV6zN4oA==,type:str]
    HOMEPAGE_VAR_PROWLARR_TOKEN: ENC[AES256_GCM,data:XWooNJ/WCP96sXjxFgFuKjuQC88KZPS/Hgy4dwwEgaQ=,iv:TdEyY78tRWfOCmapXKg1lfRMQgRYkQlRLwzHOHOwur4=,tag:qWeV2bxIG/58NsqLvcggGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXakVuWitQWUM4aDlNRmhJ
            YkZJWm9IZW91UitQSkpZZnFieTlUSUl5ZDNJCkxjWUhFa21jcHNpM290WlNFSGFp
            ZjUyWmEzUUVYOWd1YjZtUHpDWE5peE0KLS0tIHlQUjVNT1p4VElDT1h1eUljTVNJ
            aG81eU5rUWhtYU1OS0NrVFJNRVZHbXMKz4wfKc1iRnpQ6+juWv37/YtemuGolVvq
            Cw/ZNeDbueGWVeasVVJlq3yLkWY5WWGnk1Z8szleToRZnFDqpZ1JTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T18:59:40Z"
    mac: ENC[AES256_GCM,data:Ia4HRoD/z9SgZVaf6QJ27mzu5f7zPny33QsCThPGZ9PeKoW3M2W5HP9JFnaOEHSrpq60Lsu3swaHkgpgTeOv6XF5ZzKJOVe0Slg26ELkCB3/CKNaDtjLm36GarhrMsOXbYlQTH1x1q22iD5JYnFskEyKpxyg0Hx1mS5i7KYw3Dk=,iv:UavIES6BH3W19vqCZX3gf6pqWIWWa3GUyTxsyd/rWEo=,tag:lV05wLHahxvv2OOoI8uJBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
