apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:jE1jMxTMesvnQu2QWAqMgcHff+bEgf3/UHWR1wpgCfE=,iv:n5CiOb0FbfvF9B1FggBgpGWVqCsj3xGCs2DivnN34Kg=,tag:bRIH9bjDx0JM6h3i30gstQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:XdhFshn7wNh2C0XSywj36zOe7pUso8GHCM1EcbSMqtBe+6dq,iv:xY51KZZw5no9JKSvOvoYa6FgpxvnvcmF4LTadPSOk38=,tag:llOPbLmRLzuH/7Uqcc0hNg==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:Qj/bqZC3NLr7wM2GhAMC66kB3T70rjkFIvPtrJWActEGOZwJJYRIyA==,iv:GLYBMt8pil5oPoKij4ZtI26ANDpDfReh536GH9HwHPo=,tag:xsApfcmLmd2Ia9xsbHI4rQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:cyh36Uk=,iv:9joJjDc41q0l9r2ZL/Zur1XoQK+S5MVkyQzRqk0dGBE=,tag:r2JZsyhUqEHei6LSN9ImLA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:JJZyzRuqrcrtFG1xBx2qrwXD,iv:T8C+NmEvzQOpBnKMQj17mzA1qrUd5PMgCRE7wtr7Ci0=,tag:bt4jEmPpqzsqBBq2enWP2g==,type:str]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:aSALoJSK0sfaoAjic9GIHsSzULA=,iv:Fx3S+3qJPwhmCgEEmm22GnJ0SFHtNcMrMCajX4QpInA=,tag:bhNK3iXCAHGnp9SRy8kCZg==,type:str]
    HOMEPAGE_VAR_PROWLARR_TOKEN: ENC[AES256_GCM,data:ui95qrcANENNA4dyaX+rXOhklRojg1rsZx477IczLqc=,iv:Rj6LcMu2Qr+9+4p++M6rmc789hd6tTfiQJ8deI1CTeg=,tag:lNGUXbmJVaWY6B3cA/ZtFA==,type:str]
    HOMEPAGE_VAR_OVERSEERR_TOKEN: ENC[AES256_GCM,data:PwNJZVk8DkWm0qeRwsfnlFj4q4WEy9P+uWJfU+ulb2L/+fPwpRZzH5gN8DC7k8dqxletdj4Wn8w5nsAhmn8g74EdSSQ=,iv:udVFwxWQOG1To3s0G7A24bAdkZhQJQmPKd6X9psNoxI=,tag:POD8Yp+ggtw4mGF3EOiJhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMkdQZnIrdzBHK2ZjR0M2
            NUxGdVRabjcxRkF5ZXo5THBLdG9jTlRuN1FnCko1RVRZQis5OURDUEpUUkdCOUxP
            MnBSUVhIR29SS0QzWkFHOHhJV0NHa3MKLS0tIHhycjNScGl1ZXVsR0FRVnlLbExO
            d3VERnIvMmZqY1NLRnhka0NLWkZ6YW8KTxGneVzosNZuTMg8IBg60HED4d/PPsHH
            Epi7Koni8OyPAkYxd5WVvuY3tx0a/YR4VGKbavAUKeAAE73mY6fS3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T04:04:34Z"
    mac: ENC[AES256_GCM,data:qr2rG/HTooaUfVNTGrzcvRXEUCtj3wROgbYANcOdiNEdHi7Eem1ImhbJG8aR9FhKIVLH6D84G64yDPLTDVJbR9Gg9lSc0LH2WRCeJWjPzkz8L/mDMQaRfnS9e6MuF8UavIpWNVI1NXxid1PM2CEWGr3j/UFa6K7QwkYzZMHFOqI=,iv:JH7ndJiIswke7IW4LXDi2woyx/RgL/xkphUYBAVVByQ=,tag:wAFrlOlI+3uyCxTPrhnoDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
