---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  template:
    spec:
      containers:
      - name: discord-bot
        image: jgilfoil/mymindinai-discordbot:v0.0.18
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: discordbot-config
              key: LOG_LEVEL
