apiVersion: v1
kind: Secret
metadata:
    name: discordbot-secrets
    namespace: mymindinai
type: Opaque
data:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:CRC4L5swRNG58d/e1M+2o25nIt0J1sh0C2rYCyPoyODP0oA53D2fmwNiW/LTm1R/o5HvzQ2NyRHj3ASuGXmL5PX/lNr+ngw868lrPneG31vuJ+LryrppR/hx6hctFzGp4eTm4A==,iv:Bg7K1sc4t6dQhd8Fx4ylOB0fvEQr+8ooBTrzq0CnTDg=,tag:4XvNwIXzqzW7WuZ5nBZDiw==,type:str]
    MIDJOURNEY_BOT_ID: ENC[AES256_GCM,data:JXeCuTwdakzKTRCPdHE5XuJH2hwL1MW5M8g6dA==,iv:1y5SxIUbso3W5O6rsh3lNBHd35YniNpE+hMqWi8n+W0=,tag:EhYv6tSUqzJ1ih7GnKmROw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRGRwNGJjbGRoRmZNcjdE
            N0luVlljQ3pPRit3VlVLUkVCcVE3TWw1amtrCkJWZG8rdDB0ZENyK3A4elU5TjBx
            QzA1YXVDRklNWUhsOFhrR2l4NEN1SGcKLS0tIElucTdybVJzOXBhMjN6c3RGQ0tw
            dmkyUzJUMWNSVW1ob2RjK1lwN0hQbGcKEA6XKCkkb6KCVGhyxA1i9X0HEh0dhdYQ
            mKfaJIxdb88bkswgXUGsG8y5vOFToj7MbLtrFktLZsCimwJN9UOE/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T05:33:29Z"
    mac: ENC[AES256_GCM,data:DvusUhL2+jb0C82NPvGKmLS3R0qIh+C2zc2GExT/iFRLqE479oTmiPrLw3BL0332fj8EQ+avy/H7TjYOG5bRoQTN3406beuviA+TD5JQlnvFLQnG1xMV6cSnn2Zr99utV8bszUhfu/dKR+urh3ZjWIbzlcMT6M1pT/pLDDsgA4w=,iv:yoqP3BuohrT14c2AbPwtmveQI5Fbk7Jw4sJGSEisz6g=,tag:x65DDtsxmmlUVlZuNGrzqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
