apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Cdx8g4eIJnapRQA+ixHt75xOFBaglGxBhuJID0Ey41q7op+fl+6U0g==,iv:kOTNjGLQsM+aXA5s+mU21X0IR7inybz0pyPyNX0mksU=,tag:pMExBoRyICVd69kf7hCL9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhK3ZVK1FmUWhILzVSN3pF
            d3Fkbmh3R0VnREV3RUVvK1FwSzliZ0dnRGxNClhucEViMVd4OC91SkhIT25KODFk
            S2pjTThPQTBiTVJWb29vay9WTGlEeU0KLS0tIDNqY3FOcnBtcXJPeGpyNlhWK0JB
            b2NQdXoyenZaS1YyMU5GQm1FY3IxSGsKdmjRYUnKDRV2SyQtQum0wrrve/b4+QKi
            28Fc5p+W0skmL6L/sz30s3UApbPnUjYc83u8frdYcj2x19OoH3QoMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T23:16:04Z"
    mac: ENC[AES256_GCM,data:QZg2apk8/Qs6cxFZdy9sN3OvYtNQL6MRZbWlbbhwFBIe1VejntdRUxz0FfYYPYcFsrmA/uwqwizaUgjzT70aVNHDNeqwjaF8nWmqMjkGifwaM7xpDhWZpEvlvO1N33PV3qcP2/NQM/HAeVsd1lgw/a6LJIGnPbQBvXwiOXTZ39E=,iv:3kGp2VoMuSPIDuaYXOoth8+m2xuXUR77A7X+eAIQogE=,tag:er5FeRifQSmRrpgt6RjXEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
