apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app limesurvey
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: limesurvey
      # Get the latest version from https://github.com/martialblog/helm-charts/tree/main/charts/limesurvey
      version: "0.9.0" # Please verify and update to the latest chart version
      sourceRef:
        kind: HelmRepository
        name: martialblog
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    limesurvey:
      admin:
        user: admin
        # password: ${LIMESURVEY_ADMIN_PASSWORD} # Sourced from secret.sops.yaml
        # Use existingSecret to load admin password
        existingSecret: limesurvey-secret # Name of the k8s secret we will create
        existingSecretAdminPasswordKey: LIMESURVEY_ADMIN_PASSWORD
        email: admin@${SECRET_DOMAIN}
      publicUrl: https://survey.${SECRET_DOMAIN}/
      listenPort: 8080 # Explicitly set, though it's the default
    # Configure persistence to use the PVC we defined
    persistence:
      enabled: true
      existingClaim: "limesurvey-uploads-pvc"
      # subPath: "" # Set this if your NFS PV corresponds to a subfolder on the NAS for uploads
      # Remove size and storageClassName as we use existingClaim
    mariadb:
      enabled: true
      auth:
        # Use existingSecret to load DB passwords
        # The secret keys should now match the Bitnami MariaDB chart defaults:
        # mariadb-root-password, mariadb-password
        existingSecret: limesurvey-secret # Name of the k8s secret
        database: limesurvey
        username: limesurvey
      primary:
        persistence:
          enabled: true
          existingClaim: "limesurvey-mariadb-pvc"
    service:
      # type: ClusterIP # This is the default
      port: 80 # Service will listen on port 80, chart should target pod port 8080
    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        # cert-manager.io/cluster-issuer: letsencrypt-production # Uncomment if using cert-manager
      hosts:
        - host: "survey.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix # Using Prefix as it's generally more common and clear
              # backend serviceName and servicePort are handled by the chart's ingress template
      tls:
        - hosts:
            - "survey.${SECRET_DOMAIN}"
          # secretName: was removed by user, so it stays absent
    # resources: # Adjust as needed
    #   requests:
    #     cpu: 200m
    #     memory: 256Mi
    #   limits:
    #     cpu: 500m
    #     memory: 512Mi 