apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: limesurvey-internal
  namespace: default # Matches the namespace of the HelmRelease
  annotations:
    kubernetes.io/ingress.class: internal # Or your specific internal ingress class name
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Utilities # Or another suitable group from your homepage config
    gethomepage.dev/name: LimeSurvey
    gethomepage.dev/icon: limesurvey.png # You might need to find/host a suitable icon
    gethomepage.dev/description: "Survey Application"
    # Add any other necessary annotations for your internal ingress controller
spec:
  rules:
    - host: survey.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: limesurvey
                port:
                  number: 80
  tls:
    - hosts:
        - survey.${SECRET_DOMAIN}