---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: limesurvey-uploads-pvc
  labels:
    app.kubernetes.io/name: "limesurvey"
spec:
  accessModes: ["ReadWriteOnce"] 
  resources:
    requests:
      storage: 500Mi
  storageClassName: ceph-block

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: limesurvey-mariadb-pvc
  labels:
    app.kubernetes.io/name: limesurvey
    app.kubernetes.io/component: mariadb
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi # Adjust as needed for the database
  storageClassName: ceph-block