apiVersion: v1
kind: Secret
metadata:
    name: limesurvey-secret
    # Ensure the secret is in the default namespace
    namespace: default
stringData:
    LIMESURVEY_ADMIN_PASSWORD: ENC[AES256_GCM,data:cwyTXX1eiVg5OaOL,iv:mrju2r1uCHlfN3NqlIK/gxw75XCLJwlvBTHG1TAfORk=,tag:A+hakGQ515lgsETSET91Tw==,type:str]
    LIMESURVEY_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:tpVXeFWfpjelg3mu,iv:/6F1QugOG4WblU84a987Ek1DHunnM6h4fCBX08bAx24=,tag:6UNmVzY1pEHdlFtJy0OaXw==,type:str]
    LIMESURVEY_DB_PASSWORD: ENC[AES256_GCM,data:rBS3wFuy86vnrVYg,iv:M9zMT7R2mC1i4OCRsK+pWefXjLAUA3CtjYeR/cD7kCA=,tag:6iMf3Cj6uP2/vFDFGWttsQ==,type:str]
sops:
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Vmh6K1Qvd2xjbkJrcCtD
            SVQ0R0hVam5VK21SNi8zWk1qOFpZSkF3b1hNCndmbDlESXJGdHkwNGZMMUYya2xJ
            RE5aZ3g2Z0ZqZUlZYkxWNzlpRGc1N3MKLS0tICtUYnBOVmpXSG53b2E1UWVDSEth
            dXlhTSt1RnJ1Y3Q4ajZQM0JnbUtiMUUKMqB3VShQt7EQH41Jv6LT6J4Qwo/mYVZ/
            huKHpjJBpOFDtLAtr8NFE8ukAehkrtgzAa9J2Ukwg+SLihReR+aRVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-29T00:49:13Z"
    mac: ENC[AES256_GCM,data:3/kG55P7kdPEKTZ8eUmdxDLvW7HAsVLp/lYYM7gC9egGAkYbqobYD5iAGwCvQji82f5lh0jcbaXmKYGRpBuFXNRPoQPVUKDXONIdk5kbc69jwOeXWoZoCyEwo4U5B/7qwPbY/O/upWYWutcB/IRWCx58i8d+2gGd5tugQ/tq/FM=,iv:n5znKcQpPcIERpWf7BdeEke58+aOBJM7uQgzeFofWdE=,tag:9RXSJHJI3nAjPoUce1NDKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
