apiVersion: v1
kind: Secret
metadata:
    name: limesurvey-secret
    # Ensure the secret is in the default namespace
    namespace: default
stringData:
    #ENC[AES256_GCM,data:5fY0veLnekb50SI+Y0YiauY6xnk9Tp8DJvVUVYR+YSFPIdykwpbMWJQqFKChsQ==,iv:o7XjuGmx0igrpeFglPebPVzT7rKUYKJVt2cyQwNOAxU=,tag:P+b8ye8WVQRO8GHO+7dnVw==,type:comment]
    LIMESURVEY_ADMIN_PASSWORD: ENC[AES256_GCM,data:Xpg0Nwo8HngxTDwcThuIKQ==,iv:A6IseBxmWhPfCPKtWoygaGJWB9cJVShN3qR8xe2Vv8k=,tag:kkNjOMmsBup+zZFGvZ6v4w==,type:str]
    #ENC[AES256_GCM,data:pOtwEjv+9VhRrN24nkfQlcqp/ntVaVQ56V6NyCXQGww8u9qxlJEqMFpSS8LipUcErgGw3Y8=,iv:Ce6xR+bdWEe5IeX1DFqldCYaDk18bqJJl+PPUJmuw3g=,tag:Uzi12fTotglmVSW4Ik3cTQ==,type:comment]
    mariadb-root-password: ENC[AES256_GCM,data:bfKEU4ZhN2cOxrNp,iv:4jUoynj2QoieXhBjExe67n0VthGvbRmzAfNHUZpcmo8=,tag:zPi+UTSCMea1N2gjmrvaZA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:4gNUsOcz4tu1qonT,iv:b2E+hnDoUvoQCq8I2yFA00GjjBBFfQutO84bwhRxeUY=,tag:d8UaKNYNGfKJAChWB3tmeg==,type:str]
sops:
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHODJEN3htTndHZVFoME8w
            OGs5d0tvRnhjY2V4SlJGWWZ3K0JzeDJkV2lzCkgxR0dFa2RSbEpHTmtLTU0zekcz
            ZVZHeHl4aTJmb1lRdDhqQmd5aCtpNjAKLS0tIHY2TVJNN0pYWjdrSjM2NnRrZEdB
            MjAyZTZqaSsrRTRldSthclFzRCtkUDgKbTV0yQAO87EA2sNvDB7Pg6qp7RcstL8V
            cToE/YX2uRkwa8Wt+takTKeqxT0TrG7ZqhXGorFiC4OFB+jPCjHykA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-29T01:46:44Z"
    mac: ENC[AES256_GCM,data:PC2MmwM4lTS8qtnP4ZUO540O2lPGRCWCuUr02GLNJjdUcOx5Aw6g/AguCkM9d5+mGwVZZX3meq7tZEvP9vmI62BMOoEdE2N1Lziky1f5Xh8se+G+cXt2L26t6bRzLeS0bnNRNrdxqviYX8j3j6yvT690qx9LuWtfX6PtrzKbLfw=,iv:ZVBfBEc7Ba3mnmfrM2VF5r3tA/NiMLH+cBobh0LaXpA=,tag:1RQAQBKuUH8NCbFbkjlKNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
