apiVersion: v1
kind: Secret
metadata:
    name: limesurvey-secret
    # Ensure the secret is in the default namespace
    namespace: default
stringData:
    #ENC[AES256_GCM,data:lzoHzIAyL9f6Hlduv1zrTRtJN4UxiCqvy/y33mykG9HAZ3WAOCELpgvxXFPgoA==,iv:JugV5Vsds7lDDTFwoP9xwRyp1seKfCvXufwFm2BO/k0=,tag:qI6kWvFQmShX+tTotUID7g==,type:comment]
    LIMESURVEY_ADMIN_PASSWORD: ENC[AES256_GCM,data:ZJywKb8NW4fyBHOk,iv:OP+dVOkyFjDNsdG+q/fqMP/X+su0IuRCv5uTfNHQQSM=,tag:JsNJ7ufZ3D/JxamjL+X2Xw==,type:str]
    #ENC[AES256_GCM,data:UrnnG9BVqe2OlxpC5OXC62KDcXXILKuk++XPDbLTelNhLm+aaYUgLSRbIQxQkLrUth8tjPk=,iv:VD7OkKEAuo9BC+ppJBuL9o6RqG03hTH+nawtQqFc4Y4=,tag:/WLrcCYFaX3K3817kyUF4w==,type:comment]
    mariadb-root-password: ENC[AES256_GCM,data:sYXFJ01yJuIdH3GZ,iv:g1rCrGQq0Nuw70ZcRnW3iuZ66FVdhWPMdg/uLDLgUYY=,tag:L5O5STNnxf57ze9kqZNV3A==,type:str]
    mariadb-password: ENC[AES256_GCM,data:qQoSNnDXLryN7cg6,iv:yKIeze/z79wd7KR5SbvKL8Yt7tOK1RiwgbwFjapcNw4=,tag:WkXOrka0jyzGksHoQ/gxxw==,type:str]
sops:
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SWxmSTVpVXdMN1FYaEd3
            TVNpWldTU3J2Y0YzREJrZ2NMWmk2bHcyTm1NCnluUHFUcnpwVDR5RVZBRElTSDBI
            dzJaU3QyUE9FWnRiL1RQdS9DZGJrRXMKLS0tIFF4bGRoZDYyL0Z6NjAyM0RFRzBw
            RnR2aUZ0Y2hsdzZ4T0ZBUzlTU2UxRXMKAxBEiVvf3b3ARiiU/vDLrXmc2VYLABHr
            GUft5iICt/5owp+xCRE6ZD2t8Zk5cszMHI7COzmecV2LsgAtGugf8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-29T01:10:51Z"
    mac: ENC[AES256_GCM,data:pWVxBRPZ0Oe9Cb7Cu7XvQDVskSTJ6Xqy0QMNGW+wbZQoTmqXLLbLNc4vG9WSZCF4FxpnS9VB7m4N3xcQaZKPVx2eL+RkIFqc/jgWANo1/VeNl4p/4jibok8hwR/F+YntxgP66Jlnonv1xWrmsIKjBDvKMOxkGNfq8yosn6AedJE=,iv:tahZscMkYQv9RMaFX3OGE2smEvJpYTc63n+oXSKYkCw=,tag:srJQVl8CB3JZT22/7bOSRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
