---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Kubeconform"

on:
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**"]

env:
  KUBERNETES_DIR: ./kubernetes

jobs:
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@9f17989bd508c794353d974d1756f23b0bcf10c1 # main

      - name: Setup Workflow Tools
        run: brew install fluxcd/tap/flux kubeconform kustomize

      - name: Run kubeconform
        shell: bash
        run: bash ./scripts/kubeconform.sh ${{ env.KUBERNETES_DIR }}
